;  SID Analysis program STATION INI file
;    SIDAnalStations.ini
;    JUL 2015


[FREQUENCY]
NAA=24.0kHz (NAA)
NLK=24.8kHz (NLK)
NPM=21.4kHz (NPM)
NWC=19.8kHz (NWC)
HWU=15.1kHz (HWU)
FTA=16.8kHz (FTA)
ICV=20.3kHz (ICV)
JXN=16.4kHz (JXN)
GQD=22.1kHz (GQD)
GBZ=19.6kHz (GBZ)
GBR=16.0kHz (GBR)
DHO=23.4kHz (DHO)
CFH=73.6kHz (CFH)
NSW=19.8kHz (NSW)
HVU=23.0kHz (HVU)
FTX=18.0kHz (FTX)
VTX3=18.2kHz (VTX3)
NSS=21.4kHz (NSS)
NAU=40.8kHz (NAU)
NML=25.2kHz (NML)
VTX=18.2kHz (VTX)
FQE=18.1kHz (FQE)
TBB=26.7kHz (TBB)
NSY=45.9kHz (NSY)
DCF=77.5kHz (DCF)
NLM=25.2kHz (NLM)
JJI=22.2kHz (JJI)
NDT=22.2kHz (NDT)
NRK=37.5kHz (NRK)
NWC=19.8kHz (NWC)
GQ2=22.1kHz (GQZ)
NAA=24.0kHz (NAA)

_HWU=khz (_HWU)
_NLK=24.8khz (_NLK)
