;  SID Analysis program CONTROL file
;    SIDAnalControl.ini
;    May 2002


[FILES]
BaseDirectory = C:\0_SID_Data\

[ALLOCATIONS]
MaxObservers = 30
MaxEvents = 300
MaxEventsSEC = 500
MaxCorrelations	= 1000
